name: Multiple Jobs

on:
  push

jobs: 
  build_job_1:
    runs-on: self-hosted
    steps:

    - name: Install Cowsay program
      shell: powershell
      run: choco install cowsay -y

    - name: Execute cowsay CMD
      shell: powershell
      run: cowsay "Run for cover, I am dragon" | Out-File -FilePath dragon.txt -Encoding utf8

    # - name: Upload file to Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: dragon-text-file
    #     path: dragon.txt


  test_job_2:
    needs: build_job_1
    runs-on: self-hosted
    steps:

    # - name: Download dragon text file
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: dragon-text-file

    - name: Test file exists
      shell: powershell
      run: Select-String -Path dragon.txt -Pattern "dragon"


  deploy_job_3:
    needs: test_job_2
    runs-on: self-hosted
    steps:

    # - name: Download dragon text file
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: dragon-text-file

    - name: Read file
      shell: powershell
      run: Get-Content -Path dragon.txt

    - name: Deploy
      shell: powershell
      run: Write-Output "Deploying .... in the self-hosted machine"

  
